repos:
  # SwiftLint
  - repo: https://github.com/realm/SwiftLint
    rev: 0.62.2
    hooks:
      - id: swiftlint
        files: \.swift$
        types: [file, swift]
        entry: swiftlint
        language: system
        args: [--config, ios/.swiftlint.yml]

  # SwiftFormat
  - repo: local
    hooks:
      - id: swiftformat
        name: SwiftFormat
        entry: swiftformat
        language: system
        files: \.swift$
        types: [file, swift]
        args: [--config, ios/.swiftformat, ios/]
